import torch
import numpy as np
from ssd_extractor import ModelOutputs

class UnitCAM:
    """Unit Class Activation Mapping (UnitCAM)
    UnitCAM is the foundation for implementing all the CAMs
    Attributes:
    -------
        model: The wanna-be explained deep learning model for image classification
        num_classes: Total classes in the dataset
        use_cuda: Whether to use cuda
    """

    def __init__(self, model, num_classes, use_cuda):
        self.model = model
        self.num_classes = num_classes
        self.model.eval()
        self.cuda = use_cuda
        if self.cuda:
            self.model = model.cuda()

    def forward(self, input_features):
        """Forward pass
        Attributes:
        -------
            input_features: An image data input to the model
        Returns:
        -------
            Forward-pass result
        """
        return self.model(input_features)

    def _extract_features(self, input_features, print_out, bbox, index, zero_out=None):
        """Extract the feature maps of the targeted layer
        Attributes:
        -------
            input_features: An image input to the model
            bbox: Targeted bounding box
            index: Targeted output class
            print_out: Whether to print the maximum likelihood class
                (if index is set to None)
            zero_out: Whether to set the targeted module weights to 0
                (used in Ablation-CAM)
        Returns:
        -------
            transformed_input: The preprocessed input image before inputing to the model
            features: The feature maps of the targeted layer
            output: The forward-pass result
            raw_boxes_per_scale: All the detected boxes before being thresholded
            num_classes: Total classes
            index: The targeted class index
            anchors: Default anchors generated by the model
        """
        self.extractor = ModelOutputs(
            self.model, self.num_classes, bbox
        )
        if self.cuda:
            if zero_out:
                transformed_input, features, output, raw_boxes_per_scale, anchors = self.extractor(input_features.cuda(), bbox, zero_out)
            else:
                transformed_input, features, output, raw_boxes_per_scale, anchors = self.extractor(input_features.cuda(), bbox)
        else:
            if zero_out:
                transformed_input, features, output, raw_boxes_per_scale, anchors = self.extractor(input_features, bbox, zero_out)
            else:
                transformed_input, features, output, raw_boxes_per_scale, anchors = self.extractor(input_features, bbox)

        if index is None:
            index = output[0]['labels'][[torch.allclose(output[0]['boxes'][idx], bbox) for idx in range(len(output[0]['boxes']))]]
            if print_out:
                print(f"The index has the largest maximum likelihood is {index}")

        return transformed_input, features, output, raw_boxes_per_scale, index, anchors
 
    @staticmethod
    def _cam_weighted_sum(cam, weights, target, ReLU=True):
        """Do linear combination between the defined weights and corresponding
        feature maps
        Attributes:
        -------
            cam: A placeholder for the final results
            weights: The weights computed based on the network output
            target: The targeted feature maps
        Returns:
        -------
            cam: The resulting weighted feature maps
        """
        try:
            for i, w in enumerate(weights):
                cam += w * target[i, :, :]
        except TypeError:
            cam += weights * target[0:1, :, :]

        if ReLU:
            cam = np.maximum(cam, 0)

        cam = cam - np.min(cam)
        cam = cam / (np.max(cam) + 1e-9)
        return cam

    def __call__(self, input_features, bbox, index=None):
        """Abstract methods for implementing in the sub classes
        Attributes:
        -------
            input_features: An image data input to the model
            bbox: Targeted bounding box
            index: Targeted output class
        """
        return NotImplementedError