name: detex
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.7
  - pip=21.2.4
  - cudatoolkit=11.3.1
  - pytorch=1.10.0
  - torchvision=0.11.1
  - torchaudio=0.10.0
  - tqdm
  - jupyterlab
  - matplotlib
